name 'workstation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version '0.1.0'

depends 'ws_users'
depends 'ws_zsh'
depends 'ws_dotfiles'
depends 'ws_vim'
depends 'ws_ruby'
depends 'the_silver_searcher'
depends 'apt'
depends 'chef-sugar'
